import createClient from "openapi-fetch";
import type { paths, components } from "./apischema"; // generated by openapi-typescript
export type SimplePollingEvent = components["schemas"]["Event"];
export const loadEventsGenerated = async () => {
  const client = createClient<paths>({ baseUrl: "http://localhost:4000" });
  const { data, error } = await client.GET("/eventsapi/events", { params: { query: { limit: 10 } } });
  if (error) {
    throw new Error(error);
  }
  return data.items;
};
