openapi: 3.0.0
info:
  title: Events API
  version: 1.0.0

paths:
  /eventsapi/events:
    get:
      summary: Get list of events
      operationId: getEvents
      parameters:
        - name: limit
          in: query
          description: Maximum number of events to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsCollection"
    post:
      summary: Create a new event
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully
components:
  schemas:
    EventsCollection:
      type: object
      description: A list of events.
      required:
        - items
      properties:
        items:
          description: Each Event object
          type: array
          items:
            $ref: "#/components/schemas/Event"
    Event:
      type: object
      required:
        - title
        - dates
        - id
      properties:
        title:
          type: string
        id:
          type: string
        location:
          type: string
          nullable: true
        dates:
          type: array
          items:
            type: string
            format: date-time
