import createClient from "openapi-fetch";
import type { paths } from "../schema"; // generated by openapi-typescript
import dns from "node:dns";
dns.setDefaultResultOrder("ipv4first");
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

const loadEvents = async () => {
  const client = createClient<paths>({ baseUrl: "http://127.0.0.1:4000" });
  // const client = createClient<paths>({ baseUrl: "http://localhost:4000" });
  const { data, error } = await client.GET("/eventsapi/events", { params: { query: { limit: 10 } } });
  if (error) {
    console.log("oops");
    console.error(error);
    return;
  }
  console.log();
  console.log(data.items[0]);
};

loadEvents();
