name: Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm install --prefix server
          npm install --prefix client
          npm run lint --prefix server
          npm run lint --prefix client
          echo $?
        if: success()
        env:
          CI: true
